name: Python package and pytests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}        
    - name: Build python binaries & install the local package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Install dev dependencies
      run:
        python -m pip install -r requirements-dev.txt
    - name: Run tests
      # cd to avoid name conflict between the local python module name and the package name
      run: |
        cd python_tests
        python -m pytest
        
